pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: squash
        strict: smart
        strict_method: rebase
      delete_head_branch: true
