---
- name: Generate static config file
  template:
    dest: "{{ traefik_configfile_static }}"
    src: static.yaml.j2
    lstrip_blocks: true
    trim_blocks: true
    owner: root
    group: root
    mode: 0640
  register: _traefik_restart

- name: Generate dynamic config file
  template:
    dest: "{{ traefik_configfile_dynamic }}"
    src: dynamic.yaml.j2
    lstrip_blocks: true
    trim_blocks: true
    owner: root
    group: root
    mode: 0640
