---
- name: Generate static config
  template:
    dest: "{{ traefik_configfile_static }}"
    src: traefik.yaml.j2
    lstrip_blocks: true
    trim_blocks: true
    owner: "{{ traefik_user }}"
    group: "{{ traefik_group }}"
    mode: 0640
  register: _traefik_restart
  notify: traefik_restart

- name: Create directory for dynamic configs
  file:
    path: "{{ traefik_configdir_dynamic }}"
    state: directory
    owner: "{{ traefik_user }}"
    group: "{{ traefik_group }}"
    mode: 0755

- name: Generate default dynamic config
  template:
    dest: "{{ traefik_configdir_dynamic }}/default.yaml"
    src: default.yaml.j2
    lstrip_blocks: true
    trim_blocks: true
    owner: "{{ traefik_user }}"
    group: "{{ traefik_group }}"
    mode: 0640
