---
# tasks file for traefik role
- name: Check required variables
  import_tasks: assert.yml
  tags: traefik, assert

- name: Run pre-installation tasks
  import_tasks: preinstall.yml
  tags: traefik, traefik-preinstall

- name: Run configuration tasks
  import_tasks: config.yml
  tags: traefik, traefik-config

- debug:
- name: Run install method tasks
  import_tasks: install_container.yml
  tags: traefik, traefik-install
