---
# tasks file for traefik role
- name: Ensure docker networks state
  docker_network:
    name: "{{ item }}"
    state: present
  loop:
    - "{{ traefik_network }}"
    - "{{ docker_socket_proxy }}"
  tags: traefik, traefik-networks

- name: Ensure traefik data directory state
  become: true
  file:
    path: "{{ traefik_data }}"
    state: directory
    owner: root
    group: root
    mode: '750'
  tags: traefik, traefik-dir

- name: Ensure acme storage state
  become: true
  file:
    path: "{{ traefik_acme_storage_file }}"
    state: touch
    access_time: preserve
    modification_time: preserve
    owner: root
    group: root
    mode: '600'
  tags: traefik, traefik-acme

- name: Generate traefik config files
  become: true
  template:
    dest: "{{ item.dest }}"
    src: "{{ item.src }}"
    lstrip_blocks: true
    trim_blocks: true
    owner: root
    group: root
    mode: '640'
  loop:
    - { src: static.yaml.j2, dest: "{{ traefik_configfile_static }}" }
    - { src: dynamic.yaml.j2, dest: "{{ traefik_configfile_dynamic }}" }
  register: traefik_config
  tags: traefik, traefik-config

- name: Launch docker-socket-proxy
  docker_container:
    name: "{{ docker_socket_proxy }}"
    image: tecnativa/docker-socket-proxy:latest
    pull: true
    ignore_image: false
    state: started
    recreate: false
    restart: false
    restart_policy: unless-stopped
    container_default_behavior: "{{ (ansible_version.full is version('2.10', '>=')) | ternary('compatibility', omit) }}"
    networks:
      - name: "{{ docker_socket_proxy }}"
    networks_cli_compatible: true
    network_mode: default
    security_opts:
      - no-new-privileges:true
    env:
      CONTAINERS: '1'
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  tags: traefik, traefik-socket


- name: Launch traefik container
  docker_container:
    name: traefik
    image: traefik:latest
    pull: true
    ignore_image: false
    state: started
    recreate: false
    restart: "{{ traefik_config.results.0.changed | default(false) }}"
    restart_policy: unless-stopped
    container_default_behavior: "{{ (ansible_version.full is version('2.10', '>=')) | ternary('compatibility', omit) }}"
    networks:
      - name: "{{ traefik_network }}"
      - name: "{{ docker_socket_proxy }}"
    networks_cli_compatible: true
    network_mode: default
    security_opts:
      - no-new-privileges:true
    published_ports:
      - "80:80"
      - "443:443"
    command:
      - --configfile "{{ traefik_configfile_static }}"
    env: "{{ traefik_acme_dns_provider_env }}"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "{{ traefik_data }}:{{ traefik_data }}"
    labels:
      traefik.enable: "{{ traefik_dashboard_enable | string }}"
      traefik.http.routers.traefik.service: api@internal
      traefik.http.routers.traefik.entrypoints: "{{ traefik_enable_https | ternary('websecure', 'web') }}"
      traefik.http.routers.traefik.middlewares: "{{ traefik_dashboard_middlewares }}"
  tags: traefik, traefik-container
