---
- name: Create traefik system group
  group:
    name: "{{ traefik_group }}"
    state: present
    system: true

- name: Create traefik system user
  user:
    name: "{{ traefik_user }}"
    group: "{{ traefik_group }}"
    comment: "Cloud Native Application Proxy"
    home: "{{ traefik_home }}"
    create_home: false
    shell: /bin/false
    state: present
    system: true

- name: Create traefik data directory
  become: true
  file:
    path: "{{ traefik_home }}"
    state: directory
    owner: "{{ traefik_user }}"
    group: "{{ traefik_group }}"
    mode: 0755

- name: Ensure acme storage state
  become: true
  file:
    path: "{{ traefik_acme_storage_file }}"
    state: touch
    access_time: preserve
    modification_time: preserve
    owner: "{{ traefik_user }}"
    group: "{{ traefik_group }}"
    mode: 0600
