---
dependency:
  name: shell
  command: ansible-galaxy role install bonddim.docker
driver:
  name: lxd
lint: |
  set -e
  ansible-lint
platforms:
  - name: instance
    url: "${LXD_HOST:-unix:/var/snap/lxd/common/lxd/unix.socket}"
    source:
      alias: "${MOLECULE_DISTRO:-ubuntu/20.04}"
provisioner:
  name: ansible
  env:
    INSTALL_METHOD: "${INSTALL_METHOD:-binary}"
verifier:
  name: ansible
  env:
    INSTALL_METHOD: "${INSTALL_METHOD:-binary}"
