---
dependency:
  name: galaxy
driver:
  name: lxd
lint: |
  set -e
  ansible-lint --exclude .github --exclude molecule -p
platforms:
  - name: instance
    source:
      alias: "${MOLECULE_DISTRO:-ubuntu/20.04}"
provisioner:
  name: ansible
  env:
    INSTALL_METHOD: "${INSTALL_METHOD:-binary}"
verifier:
  name: ansible
  env:
    INSTALL_METHOD: "${INSTALL_METHOD:-binary}"
