---
dependency:
  name: galaxy
driver:
  name: lxd
lint: |
  set -e
  yamllint .
  ansible-lint -x 701 -p .
platforms:
  - name: instance
    source:
      alias: "${MOLECULE_DISTRO:-ubuntu/18.04}"
provisioner:
  name: ansible
verifier:
  name: ansible
