---
name: Molecule

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - '**.md'
  pull_request:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  molecule:
    # skip job on pull requests from base repository
    if: github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: bonddim.traefik
    strategy:
      matrix:
        install_method:
          - binary
          - container

    steps:
      - uses: actions/checkout@v2
        with:
          path: bonddim.traefik
      - uses: bonddim/action-lxd-init@stable
      - name: Install dependencies
        run: sudo python3 -m pip install --no-cache-dir --requirement .github/workflows/requirements.txt
      - run: molecule test
        env:
          INSTALL_METHOD: ${{ matrix.install_method }}
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: true
